controllers:
  resource: ../src/Controller/
  type: attribute
retailcrm_orders:
  path: /retailcrm/orders
  controller: App\Controller\RetailCRMController::getOrders

retailcrm_orders1:
  path: /retailcrm/customer/{email}/orders
  controller: App\Controller\RetailCRMController::getCustomerOrders

retailcrm_orders2:
  path: /retailcrm/user/{email}/profile
  controller: App\Controller\RetailCRMController::getUserProfile

retailcrm_orders3:
  path: /retailcrm/product/{productId}/{color}/{size}
  controller: App\Controller\RetailCRMController::getProductDetails
retailcrm_orders4:
  path: /retailcrm/product/{productId}
  controller: App\Controller\RetailCRMController::getProduct
retailcrm_orders6:
  path: /retailcrm/products/{groupId}
  controller: App\Controller\RetailCRMController::getProducts_category

get_uuid:
  path: /uuid
  controller: App\Controller\BaseController::uuid_get

retailcrm_orders7:
  path: /retailcrm/category
  controller: App\Controller\RetailCRMController::getCategory
